#  1.3 행렬의 연산

예제 1-3

In [1]:
import numpy as np
# np.array() : 벡터 또는 행렬을 나타냄
A = np.array([[1,0],[2,1],[4,3]])
B = np.array([[4,3],[1,1],[0,2]])

# A + B
print("A+B = \n", A+B)
print("\n")

# A-B
print("A-B = \n", A-B)
print("\n")

# 5B
print("5B = \n", 5*B)

A+B = 
 [[5 3]
 [3 2]
 [4 5]]


A-B = 
 [[-3 -3]
 [ 1  0]
 [ 4  1]]


5B = 
 [[20 15]
 [ 5  5]
 [ 0 10]]


예제 1-4

In [2]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# AB
# np.matmul(A, B) : 행렬  와  의 곱
AB = np.matmul(A,B)
print("AB = \n", AB)
print("\n")

# BA
BA = np.matmul(B, A)
print("BA = \n", BA)
print("\n")

# np.array_equal(A, B) : 행렬 A 와 B 가 같은지 확인
print("행렬 AB와 BA는 같은가?" , np.array_equal(AB, BA))

AB = 
 [[19 22]
 [43 50]]


BA = 
 [[23 34]
 [31 46]]


행렬 AB와 BA는 같은가? False


예제 1-5

In [3]:
import numpy as np
A = np.array([[3,0],[-1,2],[1,1]])
B = np.array([[-3,-1],[2,1],[4,3]])
C = np.array([[1,2,3],[2,0,1]])
D = np.array([1,2,3])

# (a) A+2B 계산
print("A+2B = \n", A+2*B)
print("\n")

# (b) AC 계산
# np.dot(A, B) : 행렬  와  의 곱
print("AC = \n", np.dot(A,C))
print("\n")

# (c) 3D 계산
print("3D = \n", 3*D)

A+2B = 
 [[-3 -2]
 [ 3  4]
 [ 9  7]]


AC = 
 [[ 3  6  9]
 [ 3 -2 -1]
 [ 3  2  4]]


3D = 
 [3 6 9]


# CH 1 프로그래밍 실습

1.1 주어진 행렬 A, B, C, D에 대하여 다음을 구하라.

In [4]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[-2,4],[1,3]])
C = np.array([[2,-5],[3,-2]])
D = np.array([[5,-1,3],[-4,3,-6],[-3,1,2]])

# (a)  A[2,2]+B[1,1]
print("문제 (a)의 답 = ", A[1,1]+B[0,0])
print("\n")

# (b) A^T^T
# A.T : 행렬 A 의 전치행렬
print("문제 (b)의 답 = \n", (A.T).T )
print("\n")

# (c) B^T
print("문제 (c)의 답 = \n", B.T )
print("\n")

# (d) A^T + B^T
print("문제 (d)의 답 = \n", (A.T)+(B.T) )
print("\n")

# (e) (A+B)^T
print("문제 (e)의 답 = \n", (A+B).T )
print("\n")

# (f) 3I_2 -C
# np.eye(n) :  × 크기의 단위행렬
print("문제 (f)의 답 = \n", (3*np.eye(2))-C )
print("\n")

# (g) D-5I_3
print("문제 (g)의 답 = \n", D-(5*np.eye(3)) )
print("\n")

# (h) (3I_3)D
print("문제 (h)의 답 = \n", np.dot(3*np.eye(3),D) )
print("\n")

문제 (a)의 답 =  2


문제 (b)의 답 = 
 [[1 2]
 [3 4]]


문제 (c)의 답 = 
 [[-2  1]
 [ 4  3]]


문제 (d)의 답 = 
 [[-1  4]
 [ 6  7]]


문제 (e)의 답 = 
 [[-1  4]
 [ 6  7]]


문제 (f)의 답 = 
 [[ 1.  5.]
 [-3.  5.]]


문제 (g)의 답 = 
 [[ 0. -1.  3.]
 [-4. -2. -6.]
 [-3.  1. -3.]]


문제 (h)의 답 = 
 [[ 15.  -3.   9.]
 [-12.   9. -18.]
 [ -9.   3.   6.]]


