# 2.1 가우스-조르당 소거법

예제 2-1

In [1]:
import numpy as np
from sympy import *

# 행렬 A 의 첨가행렬을 기약 행 사다리꼴로 변환
# np.hstack(A, b) : 행렬 A 에 벡터 b를 붙여 첨가행렬 만들기
# Matrix() : 행렬을 의미

A = np.array([[1,3,2],[2,2,0],[-3,1,1]])
b = np.array([[2,0,-2]])
augmented_A = Matrix(np.hstack((A,b.T)))

print("행렬 A의 첨가행렬 = \n", np.array(augmented_A))
print("\n")
print("행렬 A의 첨가행렬의 기약 행 사다리꼴 = \n", np.array(augmented_A.rref()[0]))

행렬 A의 첨가행렬 = 
 [[1 3 2 2]
 [2 2 0 0]
 [-3 1 1 -2]]


행렬 A의 첨가행렬의 기약 행 사다리꼴 = 
 [[1 0 0 1]
 [0 1 0 -1]
 [0 0 1 2]]


예제 2-2

In [2]:
import numpy as np
from sympy import *

# 행렬 A 의 첨가행렬을 기약 행 사다리꼴로 변환
A = np.array([[3,6,3],[2,1,4],[-1,3,5]])
b = np.array([[6,-1,-3]])
augmented_A = Matrix(np.hstack((A,b.T)))

print("행렬 A의 첨가행렬 = \n", np.array(augmented_A))
print("\n")
print("행렬 A의 첨가행렬의 기약 행 사다리꼴 = \n", np.array(augmented_A.rref()[0]))

행렬 A의 첨가행렬 = 
 [[3 6 3 6]
 [2 1 4 -1]
 [-1 3 5 -3]]


행렬 A의 첨가행렬의 기약 행 사다리꼴 = 
 [[1 0 0 1]
 [0 1 0 1]
 [0 0 1 -1]]


# 2.2 역행렬

예제 2-3

In [3]:
import numpy as np
# 행렬 A 의 역행렬 계산
# np.linalg.matrix_power(A, n) : 행렬 A 의 n제곱
# np.linalg.matrix_power(A, -1) : 행렬 A 의 역행렬
A = np.array([[2,3],[5,7]])
A_inv = np.linalg.matrix_power(A, -1)
print("Inverse matrix of A = \n", A_inv)

Inverse matrix of A = 
 [[-7.  3.]
 [ 5. -2.]]


예제 2-4

In [4]:
import numpy as np

# 행렬 A 의 역행렬 계산
# np.linalg.inv(A) : 행렬 A 의 역행렬

A = np.array([[1,3,2],[2,2,0],[-3,1,1]])
A_inv = np.linalg.inv(A)
print("Inverse matrix of A = \n", A_inv)

Inverse matrix of A = 
 [[ 0.16666667 -0.08333333 -0.33333333]
 [-0.16666667  0.58333333  0.33333333]
 [ 0.66666667 -0.83333333 -0.33333333]]


# 2.3 여러가지 행렬

예제 2-7

In [5]:
import numpy as np

# 행렬 A 의 전치행렬 구하기
# A.T : 행렬 A의 전치행렬
A = np.array([[-1,3],[3,7]])
A_T = A.T
print("Transposed matrix of A = \n", A_T)
print("\n")

# 행렬 B 의 전치행렬 구하기
B = np.array([[1,3,5],[7,2,9],[10,11,3]])
B_T = B.T
print("Transposed matrix of B = \n", B_T)

Transposed matrix of A = 
 [[-1  3]
 [ 3  7]]


Transposed matrix of B = 
 [[ 1  7 10]
 [ 3  2 11]
 [ 5  9  3]]


예제 2-10

In [6]:
import numpy as np

A = np.array([[1,2,0],[3,2,1],[2,-1,1]])
B = np.array([[1,-2,3],[1,4,2],[-1,0,7]])

# 행렬 AB 의 계산과 행렬 AB 의 대각합 계산
# np.trace(A) : 행렬 A의 대각합

AB = np.matmul(A,B)
tr_AB = np.trace(AB)

print("AB = \n", AB)
print("\n")
print("Trace of AB = \n", tr_AB)
print("\n")

# 행렬 BA 의 계산과 행렬 BA의 대각합 계산

BA = np.matmul(B, A)
tr_BA = np.trace(BA)

print("BA = \n", BA)
print("\n")
print("Trace of BA = \n", tr_BA)
print("\n")
print("행렬 AB와 행렬 BA는 같은가?" , np.array_equal(AB, BA))
print("tr(AB)와 tr(BA)는 같은가?" , tr_AB == tr_BA)

AB = 
 [[ 3  6  7]
 [ 4  2 20]
 [ 0 -8 11]]


Trace of AB = 
 16


BA = 
 [[ 1 -5  1]
 [17  8  6]
 [13 -9  7]]


Trace of BA = 
 16


행렬 AB와 행렬 BA는 같은가? False
tr(AB)와 tr(BA)는 같은가? True


# Ch 2 프로그래밍 실습 

2.1 가우스-조르당 소거법을 코드로 구현하여 다음 방정식의 해를 구하라.

In [7]:
import numpy as np

# 가우스-조르당 소거법을 수행하는 함수
# range(n) : 0부터 n까지 나열 
# min(i,j) : 숫자 i와 j 중 작은 값
# abs(i) : i의 절댓값
# np.zeros(n) : 0으로 이루어진 n차 정방행렬

def Gauss_Jordan_method(A):
    (n,m) = A.shape
    A = A.astype(np.float32)
    for i in range(0, min(n,m)):
    # i번째 열에서 절댓값이 최대인 성분의 행 선택
        maxEl = abs(A[i,i])
        maxRow_num = i
        for k in range(i+1, n):
            if abs(A[k,i]) > maxEl:
                maxEl = abs(A[k,i])
                maxRow_num = k
        
        # 현재 i번째 행과 최댓값을 갖는 행을 교환
        for k in range(i, m):
            tmp = A[maxRow_num,k]
            A[maxRow_num,k] = A[i,k]
            A[i,k] = tmp
        
        # 추축성분을 1로 만들기
        piv = A[i,i]
        for k in range(i, m):
            A[i,k] = A[i,k]/piv
        
        # 현재 i번째 열의 i번째 행을 제외한 모두 성분을 으로 만들기
        for k in range(0, n):
            if k != i:
                c = A[k,i]/A[i,i]
                for j in range(i, m):
                    if i == j:
                        A[k,j] = 0
                    else:
                        A[k,j] = A[k,j] - c * A[i,j]
        # 중간 과정 출력
        print(str(i+1)+"번째 반복 ")
        print(A)
    # Ax=b의 해 반환
    sol_x = np.zeros(m-1)
    for i in range(0,m-1):
        sol_x[i] = A[i,m-1]
    return sol_x

# 문제 (a)의 방정식의 해
# np.round(i) : 실수 I를 반올림

print("Solution of (a)\n")
A = np.array([[1,2,-1],[2,3,-1],[3,-2,3]])
b = np.array([[6,8,-4]])
augmented_A = np.hstack((A,b.T))
sol = np.round(Gauss_Jordan_method(augmented_A)).astype(np.int64)

print("x_1 = ", sol[0])
print("x_2 = ", sol[1])
print("x_3 = ", sol[2])
print("\n")

# 문제 (b)의 방정식의 해

print("Solution of (b)\n")
A = np.array([[1,1,2],[2,6,4],[3,1,3]])
b = np.array([[9,26,14]])
augmented_A = np.hstack((A,b.T))
sol = np.round(Gauss_Jordan_method(augmented_A)).astype(np.int64)

print("x_1 = ", sol[0])
print("x_2 = ", sol[1])
print("x_3 = ", sol[2])
print("\n")

Solution of (a)

1번째 반복 
[[ 1.        -0.6666667  1.        -1.3333334]
 [ 0.         4.3333335 -3.        10.666667 ]
 [ 0.         2.6666667 -2.         7.3333335]]
2번째 반복 
[[ 1.          0.          0.53846157  0.3076924 ]
 [ 0.          1.         -0.69230765  2.4615386 ]
 [ 0.          0.         -0.15384626  0.76923037]]
3번째 반복 
[[ 1.          0.          0.          2.9999967 ]
 [ 0.          1.          0.         -0.99999547]
 [ 0.          0.          1.         -4.999994  ]]
x_1 =  3
x_2 =  -1
x_3 =  -5


Solution of (b)

1번째 반복 
[[ 1.          0.33333334  1.          4.6666665 ]
 [ 0.          5.3333335   2.         16.666668  ]
 [ 0.          0.6666666   1.          4.3333335 ]]
2번째 반복 
[[1.        0.        0.875     3.6249998]
 [0.        1.        0.375     3.1250002]
 [0.        0.        0.75      2.2500002]]
3번째 반복 
[[1.        0.        0.        0.9999995]
 [0.        1.        0.        2.       ]
 [0.        0.        1.        3.0000002]]
x_1 =  1
x_2 =  2
x_3 =

2.2 다음 행렬 A, B, C의 역행렬을 각각 구하라

In [8]:
import numpy as np

# 문제 (a)
A = np.array([[1,0,0,1],[0,1,2,0],[0,2,1,0],[1,0,0,5]])
A_inv = np.linalg.matrix_power(A, -1)
print("Inverse matrix of A = \n", A_inv)
print("\n")

# 문제 (b)
B = np.array([[2,3],[3,4]])
B_inv = np.linalg.matrix_power(B, -1)
print("Inverse matrix of B = \n", B_inv)
print("\n")

# 문제 (c)
C = np.array([[9,-4,6],[5,-3,6],[-3,1,-2]])
C_inv = np.linalg.matrix_power(C, -1)
print("Inverse matrix of C = \n", C_inv)

Inverse matrix of A = 
 [[ 1.25        0.          0.         -0.25      ]
 [ 0.         -0.33333333  0.66666667  0.        ]
 [ 0.          0.66666667 -0.33333333  0.        ]
 [-0.25        0.          0.          0.25      ]]


Inverse matrix of B = 
 [[-4.  3.]
 [ 3. -2.]]


Inverse matrix of C = 
 [[ 0.    -0.25  -0.75 ]
 [-1.    -0.    -3.   ]
 [-0.5    0.375 -0.875]]
