# 3.1 벡터와 벡터 공간

예제 3-4

In [1]:
import numpy as np

a = np.array([1,0,3])
b = np.array([2,1,2])

# 2a+3b
print("2*a + 3*b = ", 2*a + 3*b)

2*a + 3*b =  [ 8  3 12]


예제 3-10

In [2]:
import numpy as np

# 노름을 구하는 함수
# np.sqrt(q) : sqrt {q} 계산
# np.sum() : () 안에 있는 숫자의 합

def cal_norm(vec1):
    norm_vec = np.sqrt(np.sum(vec1*vec1))
    return norm_vec

# x의 노름 계산
x = np.array([1,2,0,2])
print("Norm of x = ", cal_norm(x))

Norm of x =  3.0


# 3.2 벡터의 내적

예제 3-12

In [3]:
import numpy as np

# 내적을 구하는 함수
def cal_innerproduct(vec1, vec2):
    innerprod_vecs = np.sum(vec1*vec2)
    return innerprod_vecs

# x와 y의 내적 계산
x = np.array([1,2,3,-1])
y = np.array([0,1,2,1])
print("Inner product of x and y = ", cal_innerproduct(x, y))
print("\n")

# y와 z의 내적 계산
y = np.array([0,1,2,1])
z = np.array([2023,1,-1,1])
print("Inner product of y and z = ", cal_innerproduct(y, z))

Inner product of x and y =  7


Inner product of y and z =  0


예제 3-13

In [4]:
import numpy as np

# 내적을 구하는 함수
# np.cos() : ()의 코사인 값
# np.pi : 𝛑
def cal_innerproduct_v2(norm_vec1, norm_vec2, angle):
    denominator = 180/angle
    innerprod_vecs = norm_vec1 * norm_vec2 *np.cos(np.pi/denominator)
    return innerprod_vecs

# x와 y의 내적 계산
norm_x = 2
norm_y = 3
angle = 30
print("Inner product of x and y = ", cal_innerproduct_v2(norm_x, norm_y, angle))

Inner product of x and y =  5.196152422706632


예제 3-14

In [5]:
import numpy as np

# 코시-슈바르츠 부등식을 확인하는 함수
# np.abs() : ()의 절댓값
def check_Cauchy_Schwarz_inequality(vec1, vec2):
    innerprod_vecs = np.sum(vec1*vec2)
    norm_vec1 = np.sqrt(np.sum(vec1*vec1))
    norm_vec2 = np.sqrt(np.sum(vec2*vec2))
    check_CS_inequal = np.abs(innerprod_vecs) <= norm_vec1*norm_vec2
    return check_CS_inequal

# x와 y로 확인
x = np.array([1,-1,3])
y = np.array([1,1,3])
print("Cauchy-Schwarz inequality is", check_Cauchy_Schwarz_inequality(x,y))

Cauchy-Schwarz inequality is True


예제 3-15

In [6]:
import numpy as np

# 직교성을 확인하는 함수
def check_Orthogonal(vec1, vec2):
    innerprod_vecs = np.sum(vec1*vec2)
    check_Orthogonal = innerprod_vecs == 0
    return check_Orthogonal

# x와 y로 확인
x = np.array([2,-5,1])
y = np.array([2,1,1])
print("Orthogonal of x and y is", check_Orthogonal(x,y))
print("\n")

# y와 z로 확인
y = np.array([2,1,1])
z = np.array([4,1,-3])
print("Orthogonal of y and z is", check_Orthogonal(y,z))
print("\n")

# x와 z로 확인
x = np.array([2,-5,1])
z = np.array([4,1,-3])
print("Orthogonal of x and z is", check_Orthogonal(x,z))

Orthogonal of x and y is True


Orthogonal of y and z is False


Orthogonal of x and z is True


예제 3-17

In [7]:
import numpy as np

# 정사영을 구하는 함수
def proj_a_b(vec_1, vec_2):
    p = (np.dot(vec_1, vec_2)/np.dot(vec_2, vec_2))*vec_2
    return p

x = np.array([1, 1])
y = np.array([2, 0])
print("Projection of x onto y = ", proj_a_b(x, y))

Projection of x onto y =  [1. 0.]


예제 3-18

In [8]:
import numpy as np

# 정사영을 구하는 함수
def proj_a_b(vec_1, vec_2):
    p = (np.dot(vec_1, vec_2)/np.dot(vec_2, vec_2))*vec_2
    return p

x = np.array([4, 5])
y = np.array([6, 1])
print("Projection of x onto y = ", proj_a_b(x, y))

Projection of x onto y =  [4.7027027  0.78378378]


예제 3-22

In [9]:
import numpy as np

# 해밍 거리를 구하는 함수
# len(vec) : vec의 성분 개수
def cal_hamming_dist(vec1, vec2):
    Num_vec = len(vec1)
    hamming_dist = 0
    for i in range(Num_vec):
        if vec1[i] != vec2[i]:
            hamming_dist = hamming_dist+1
    return hamming_dist

# v와 w 사이의 해밍 거리 계산
v = np.array([0,1,1,0,1])
w = np.array([1,1,0,1,0])
print("Hamming distance = ", cal_hamming_dist(v,w))

Hamming distance =  4


예제 3-23

In [10]:
import numpy as np

# 맨하튼 거리를 구하는 함수
def cal_Manhattan_dist(vec1, vec2):
    Manhattan_dist = np.sum(np.abs(vec1-vec2))
    return Manhattan_dist

# A=(1,1), B=(3,3)이라 할 때, 두 점 A, B 사이의 맨하튼 거리 계산
A = np.array([1,1])
B = np.array([3,3])
print("Manhattan distance = ", cal_Manhattan_dist(A,B))

Manhattan distance =  4


# 3.3 벡터의 미분 

예제 3-24

In [11]:
from sympy import *
import numpy as np

# 문제 (a)
# symbols('x') : x를 미지수로 선언
# diff(f, x) : 함수 f를 x로 미분
x, y, z = symbols('x y z')
f = x*y*z

df_dx = diff(f, x)
df_dy = diff(f, y)
df_dz = diff(f, z)

gradient_f_1 = np.array([[df_dx], [df_dy], [df_dz]])
print("(a) gradient of f = \n", gradient_f_1)
print("\n")

# 문제 (b)
x, y, z = symbols('x y z')
f = x**2*y**3+z**2+exp(x*y)

df_dx = diff(f, x)
df_dy = diff(f, y)
df_dz = diff(f, z)

gradient_f_1 = np.array([[df_dx], [df_dy], [df_dz]])
print("(b) gradient of f = \n", gradient_f_1)

(a) gradient of f = 
 [[y*z]
 [x*z]
 [x*y]]


(b) gradient of f = 
 [[2*x*y**3 + y*exp(x*y)]
 [3*x**2*y**2 + x*exp(x*y)]
 [2*z]]


예제 3-25

In [12]:
from sympy import *
import numpy as np

x, y, z = symbols('x y z')
F_1 = x-y+z**2
F_2 = x*cos(y)
F_3 = y**2*exp(3*z)

# F1, F2, F3를 x로 미분
df1_dx = diff(F_1, x)
df2_dx = diff(F_2, x)
df3_dx = diff(F_3, x)

# F1, F2, F3를 y로 미분
df1_dy = diff(F_1, y)
df2_dy = diff(F_2, y)
df3_dy = diff(F_3, y)

# F1, F2, F3를 z로 미분
df1_dz = diff(F_1, z)
df2_dz = diff(F_2, z)
df3_dz = diff(F_3, z)

Jacobian_F = np.array([[df1_dx, df2_dx, df3_dx], [df1_dy, df2_dy, df3_dy], [df1_dz, df2_dz, df3_dz]])
print("Jacobian of F = \n", Jacobian_F)

Jacobian of F = 
 [[1 cos(y) 0]
 [-1 -x*sin(y) 2*y*exp(3*z)]
 [2*z 0 3*y**2*exp(3*z)]]


예제 3-26

In [13]:
from sympy import *
import numpy as np

# diff(f, x, n) : 함수 f를 x로 n번 미분
# diff(f, x, y) : 함수 f를 x와 y 순으로 미분

x, y, z = symbols('x y z')
f = x**2-y**2+z**3

d2f_dx2 = diff(f, x, 2)
d2f_dyx = diff(f, y, x)
d2f_dzx = diff(f, z, x)

d2f_dxy = diff(f, x, y)
d2f_dy2 = diff(f, y, 2)
d2f_dzy = diff(f, z, y)

d2f_dxz = diff(f, x, z)
d2f_dyz = diff(f, y, z)
d2f_dz2 = diff(f, z, 2)

Hessian_f = np.array([[d2f_dx2, d2f_dyx, d2f_dzx], 
                      [d2f_dxy, d2f_dy2, d2f_dzy], 
                      [d2f_dxz, d2f_dyz, d2f_dz2]])

print("Hessian of f = \n", Hessian_f)

Hessian of f = 
 [[2 0 0]
 [0 -2 0]
 [0 0 6*z]]


예제 3-27

In [14]:
from sympy import *
import numpy as np

# 문제 (a)
x, y = symbols('x y')
f = x**3+2*x+y**2

d2f_dx2 = diff(f, x, 2)
d2f_dy2 = diff(f, y, 2)

Laplacian_f = d2f_dx2 + d2f_dy2
print("(a) Laplacian of f = \n", Laplacian_f)
print("\n")

# 문제 (b)
x, y, z = symbols('x y z')
f = x**3*y*z**2+2*cos(y)+x*exp(y*z)

d2f_dx2 = diff(f, x, 2)
d2f_dy2 = diff(f, y, 2)
d2f_dz2 = diff(f, z, 2)

Laplacian_f = d2f_dx2 + d2f_dy2 + d2f_dz2
print("(b) Laplacian of f = \n", Laplacian_f)

(a) Laplacian of f = 
 6*x + 2


(b) Laplacian of f = 
 6*x*y*z**2 + x*y*(2*x**2 + y*exp(y*z)) + x*z**2*exp(y*z) - 2*cos(y)


# Ch 3 프로그래밍 실습

3.1 주어진 벡터 x, y, z,v, w에 대하여 다음을 구하라.

In [15]:
import numpy as np

# 노름을 구하는 함수
def cal_norm(vec1):
    norm_vec = np.sqrt(np.sum(vec1*vec1))
    return norm_vec

# 내적을 구하는 함수
def cal_innerproduct(vec1, vec2):
    innerprod_vecs = np.sum(vec1*vec2)
    return innerprod_vecs

# 해밍 거리를 구하는 함수
def cal_hamming_dist(vec1, vec2):
    Num_vec = len(vec1)
    hamming_dist = 0
    for i in range(Num_vec):
        if vec1[i] != vec2[i]:
            hamming_dist = hamming_dist+1
    return hamming_dist

# 맨하튼 거리를 구하는 함수
def cal_Manhattan_dist(vec1, vec2):
    Manhattan_dist = np.sum(np.abs(vec1-vec2))
    return Manhattan_dist

# 벡터 x, y, z, v, w
x = np.array([1,0,1,0])
y = np.array([0,2,2,0])
z = np.array([1,0,1,2])
v = np.array([1,1,1,1])
w = np.array([2,2,0,1])

# 문제 (a)
print("문제 (a)")
print("Norm of x = ", cal_norm(x))
print("Norm of y = ", cal_norm(y))
print("Norm of z = ", cal_norm(z))
print("\n")

# 문제 (b)
print("문제 (b)")
print("Inner product of x and y = ", cal_innerproduct(x,y))
print("\n")

# 문제 (c)
print("문제 (c)")
print("Inner product of z and x+y = ", cal_innerproduct(z, x+y))
print("\n")

# 문제 (d)
print("문제 (d)")
print("Hamming distance of x and v = ", cal_hamming_dist(x,v))
print("\n")

# 문제 (e)
print("문제 (e)")
print("Manhattan distance of v and w = ", cal_Manhattan_dist(v,w))

문제 (a)
Norm of x =  1.4142135623730951
Norm of y =  2.8284271247461903
Norm of z =  2.449489742783178


문제 (b)
Inner product of x and y =  2


문제 (c)
Inner product of z and x+y =  4


문제 (d)
Hamming distance of x and v =  2


문제 (e)
Manhattan distance of v and w =  3


3.2 다음과 같은 두 벡터 x, y가 이루는 각을 구하고, x의 y 위로의 정사영 proj_y x를 구하라.

In [16]:
import numpy as np

# 두 벡터가 이루는 각을 구하는 함수
# np.linalg.norm(vec) : vec의 노름
# np.arctan() : tan()의 역함수 값

def angle_to_vectors(vec_1, vec_2):
    vec_1_norm = np.linalg.norm(vec_1)
    vec_2_norm = np.linalg.norm(vec_2)
    vec_1_2_dot = np.dot(vec_1.T, vec_2)
    angle = np.arctan(vec_1_2_dot/(vec_1_norm*vec_2_norm))*360/np.pi
    return angle

# 정사영을 구하는 함수
def Proj_onto(vec_1, vec_2):
    vec_2_1_dot = np.dot(vec_2.T, vec_1)
    vec_2_dot = np.dot(vec_2.T, vec_2)
    proj_vec = (vec_2_1_dot/vec_2_dot)*vec_2
    return proj_vec

# 문제 (a)
x = np.array([[1], [0]])
y = np.array([[4], [4]])
angle = angle_to_vectors(x, y)
projxy = Proj_onto(y, x)
print("문제 (a)")
print("x와 y가 이루는 각 = ", angle)
print("x의 y 위로의 정사영 = \n", projxy)
print("\n")

# 문제 (b)
x = np.array([[1], [2], [5]])
y = np.array([[1], [-1], [2]])
angle = angle_to_vectors(x, y)
projxy = Proj_onto(y, x)
print("문제 (b)")
print("x와 y가 이루는 각 = ", angle)
print("x의 y 위로의 정사영 = \n", projxy)
print("\n")

# 문제 (c)
x = np.array([[0], [-1], [2], [2]])
y = np.array([[1], [1], [3], [2]])
angle = angle_to_vectors(x, y)
projxy = Proj_onto(y, x)
print("문제 (c)")
print("x와 y가 이루는 각 = ", angle)
print("x의 y 위로의 정사영 = \n", projxy)

문제 (a)
x와 y가 이루는 각 =  [[70.52877937]]
x의 y 위로의 정사영 = 
 [[4.]
 [0.]]


문제 (b)
x와 y가 이루는 각 =  [[67.70902963]]
x의 y 위로의 정사영 = 
 [[0.3]
 [0.6]
 [1.5]]


문제 (c)
x와 y가 이루는 각 =  [[75.52248781]]
x의 y 위로의 정사영 = 
 [[ 0.]
 [-1.]
 [ 2.]
 [ 2.]]


3.3 다음과 같이 주어진 점 P를 포함하며 법선벡터가 n인 평면이 있다고 하자. 내적을 이용하여 이 평면과 점 P'사이의 거리를 구하라.

In [17]:
import numpy as np

# 평면과 점 사이의 거리를 구하는 함수
# np.absolute() : np.abs()와 같은 함수
def dist_Pt_to_Pl(P, N_vec, PP) :
    num = np.dot((PP-P).T, N_vec)
    N_norm = np.linalg.norm(N_vec)
    dist = np.absolute(num)/N_norm
    return dist

# 문제 (a)
print("문제 (a)")
P = np.array([1, 9, 8])
N = np.array([7, 5, 2])
PP = np.array([5, 1, 9])
print("평면과 점 사이의 거리 = ", dist_Pt_to_Pl(P, N, PP))
print("\n")

# 문제 (b)
print("문제 (b)")
P = np.array([1, 4, 5, 0])
N = np.array([4, 1, 2, 0])
PP = np.array([17, 9, 4, 11])
print("평면과 점 사이의 거리 = ", dist_Pt_to_Pl(P, N, PP))

문제 (a)
평면과 점 사이의 거리 =  1.1322770341445956


문제 (b)
평면과 점 사이의 거리 =  14.62059864581149
