# 4.1 선형변환

예제 4-8

In [1]:
import numpy as np

# 합성변환의 표준행렬을 구하는 함수
# A@B : 행렬 A와 B의 곱
def cal_CompositeTransformation(Matrix1, Matrix2):
    cal_Comp_Transformation = Matrix2@Matrix1
    return cal_Comp_Transformation

A_1 = np.array([[0, 1], [-1, 2]])
A_2 = np.array([[1, 0], [2, 1]])

print("L_2*L_1 = \n", cal_CompositeTransformation(A_1, A_2))

L_2*L_1 = 
 [[ 0  1]
 [-1  4]]


예제 4-10

In [2]:
import numpy as np

# 역변환의 표준행렬을 구하는 함수
def cal_InverseTransformation(Matrix1):
    cal_Inv_Transformation = np.linalg.inv(Matrix1)
    return cal_Inv_Transformation

A = np.array([[1, 2], [1, 3]])

print("Inverse transformation of L = \n", cal_InverseTransformation(A))
print("\n")

print("L^(-1)(1,2) = \n", np.matmul(cal_InverseTransformation(A), np.array([1,2])))

Inverse transformation of L = 
 [[ 3. -2.]
 [-1.  1.]]


L^(-1)(1,2) = 
 [-1.  1.]


예제 4-12

In [3]:
import numpy as np

# 직교연산자인지 확인하는 함수
def check_OrthogonalOperator(Mat1):
    cal_mat_mul = Mat1.T@Mat1
    check_Orthogonal = np.array_equal(cal_mat_mul, np.eye(A.shape[0]))
    return check_Orthogonal

# 행렬 A로 확인
A = np.array([[0, 1, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]])

print("Orthogonal operator is", check_OrthogonalOperator(A))

Orthogonal operator is True


# 4.2 랭크 정리

예제 4-13

In [4]:
import numpy as np

# 랭크를 구하는 함수
# np.linalg.matrix_rank(A) : 행렬 A의 랭크
def Cal_rank(Mat_1):
    rank_r = np.linalg.matrix_rank(Mat_1)
    return rank_r

A = np.array([[1, 0, 1], [0, 1, 2]])
print("Rank(A) = ", Cal_rank(A))

Rank(A) =  2


예제 4-14

In [5]:
import numpy as np

# 퇴화차수를 구하는 함수
def cal_Nullity(Matrix_1):
    rank_Mat = np.linalg.matrix_rank(Matrix_1)
    Nullity_Mat = len(Matrix_1[0,:]) - rank_Mat
    return Nullity_Mat

A = np.array([[1, 1, 3, 2], [0, 1, 2, 2]])

print("Nullity(A) = ", cal_Nullity(A))

Nullity(A) =  2


예제 4-15

In [6]:
import numpy as np

# 퇴화차수를 구하는 함수
def cal_Nullity(Matrix_1):
    rank_Mat = np.linalg.matrix_rank(Matrix_1)
    Nullity_Mat = len(Matrix_1[0,:]) - rank_Mat
    return Nullity_Mat

A = np.array([[1, 1, 3, 2], [0, 2, 2, 2], [1, 1, 2, 5]])

print("Rank(A) = ", np.linalg.matrix_rank(A))
print("Nullity(A) = ", cal_Nullity(A))

Rank(A) =  3
Nullity(A) =  1


# CH 4 프로그래밍 실습

4.1 주어진 선형변환 L에 대응하는 표준행렬에 대하여 점 P에서의 L의 상을 구하라.

In [7]:
import numpy as np

# 선형변환 계산
def cal_LinearTransformation(Matrix, point):
    cal_output = np.matmul(Matrix, point)
    return cal_output

# 문제 (a)
print("문제 (a)의 실습 결과 ")
L = np.array([[1, 2, 4], [0, -1, 3]]);
p = np.array([2, -3, 5]);
print("L = \n", L)
print("P = ", p, "\n")
print("L(p) = ", cal_LinearTransformation(L, p))
print("\n")

# 문제 (b)
print("문제 (b)의 실습 결과 ")
L = np.array([[1, -1, 1], [1, 0, 1]]);
p = np.array([13, -22, -11]);
print("L = \n", L)
print("P = ", p, "\n")
print("L(p) = ", cal_LinearTransformation(L, p))
print("\n")

# 문제 (c)
print("문제 (c)의 실습 결과 ")
L = np.array([[2, 1, 4], [1, 1, 2], [0, 1, 2], [1, 1, 3]]);
p = np.array([-4, 7, 1]);
print("L = \n", L)
print("P = ", p, "\n")
print("L(p) = ", cal_LinearTransformation(L, p))

문제 (a)의 실습 결과 
L = 
 [[ 1  2  4]
 [ 0 -1  3]]
P =  [ 2 -3  5] 

L(p) =  [16 18]


문제 (b)의 실습 결과 
L = 
 [[ 1 -1  1]
 [ 1  0  1]]
P =  [ 13 -22 -11] 

L(p) =  [24  2]


문제 (c)의 실습 결과 
L = 
 [[2 1 4]
 [1 1 2]
 [0 1 2]
 [1 1 3]]
P =  [-4  7  1] 

L(p) =  [3 5 9 6]


4.2 다음 행렬 A, B, C의 랭크와 퇴화차수를 구하라.

In [8]:
import numpy as np

# 퇴화차수를 구하는 함수
def cal_Nullity(Matrix_1):
    rank_Mat = np.linalg.matrix_rank(Matrix_1)
    Nullity_Mat = len(Matrix_1[0,:]) - rank_Mat
    return Nullity_Mat

# 행렬 A
A = np.array([[1, 2, 0, 2, 1], [-1, -2, 1, 1, 0], [1, 2, -3, -7, 2], [1, 2, -2, -4, 3]]);
print("A = \n", A)
print("Rank(A) = ", np.linalg.matrix_rank(A))
print("Nullity(A) = ", cal_Nullity(A))
print("\n")

# 행렬 B
B = np.array([[1, 3, 1, 7], [2, 3, -1, 9], [-1, -2, 0, -5]]);
print("B = \n", B)
print("Rank(B) = ", np.linalg.matrix_rank(B))
print("Nullity(B) = ", cal_Nullity(B))
print("\n")

# 행렬 C
C = np.array([[1, 2, 1, 4], [0, 1, 2, 1]]);
print("C = \n", C)
print("Rank(C) = ", np.linalg.matrix_rank(C))
print("Nullity(C) = ", cal_Nullity(C))

A = 
 [[ 1  2  0  2  1]
 [-1 -2  1  1  0]
 [ 1  2 -3 -7  2]
 [ 1  2 -2 -4  3]]
Rank(A) =  3
Nullity(A) =  2


B = 
 [[ 1  3  1  7]
 [ 2  3 -1  9]
 [-1 -2  0 -5]]
Rank(B) =  3
Nullity(B) =  1


C = 
 [[1 2 1 4]
 [0 1 2 1]]
Rank(C) =  2
Nullity(C) =  2
